---
apiVersion: v1
kind: Service
metadata:
  name: weblight_ClusterIP
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    dev: {{ .Values.name }} 
