apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      dev: {{ .Values.name }}
  template:
    metadata:
      labels:
        dev: {{ .Values.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm"]
          args: ["run", "dev"]
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          {{- if .Values.Resources.enabled }}    
          resources:
            {{- toYaml .Values.Resources.resources | nindent 12 }}
          {{- end }}
          env:
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_PORT
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MONGO_DB_NAME
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: REDIS_PORT
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: REDIS_HOST
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: PORT
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
